### ISSUE TITLE
Do you really need ".idea" and ".vscode" in the git repo ?

### ISSUE THREAD

**Issue by kerzol** [sidi001/TCHAI-SIDI-TOURE-ERIC-DIPANDA#2]
Do you really need the directories ".idea" and ".vscode" in this git repo ?

You can use git ignore to ignore them.

**Comment by sidi001** [comment]
Bonjour Monsieur,
Non pas vraiment besoin, ce sont des choses qui se sont ajouté car j'utilise VsCode et Pycharm pour mes projets Python. je vais tout à l'air faire un commit car j'ai travaillé chez moi aujourd'hui(je dois bientôt voyager, j'évite la masse pour ne pas contracter le virus et compromettre mon voyage), je ferai le ignore dans mes prochains commits pour ne pas que ça accompagne le depot.

**Comment by sidi001** [comment]
Bonjour Monsieur,
Non pas vraiment besoin, ce sont des choses qui se sont ajouté car j'utilise VsCode et Pycharm pour mes projets Python. je vais tout à l'air faire un commit car j'ai travaillé chez moi aujourd'hui(je dois bientôt voyager, j'évite la masse pour ne pas contracter le virus et compromettre mon voyage), je ferai le ignore dans mes prochains commits pour ne pas que ça accompagne le depot.

**Comment by kerzol** [comment]
ok, merci pour les explications.
